#!/bin/bash
# Deploy zabbix-agent2 on Ubuntu/Debian VMs
# Usage: ./scripts/install-zabbix-agent2.sh [ZABBIX_SERVER_IP] [HOSTNAME]
#
# Installs zabbix-agent2 natively (NOT in Docker), enables Docker plugin.
# The agent will auto-register with Zabbix server.
#
# If Zabbix server runs in Docker, pass the host IP so agent can reach it.
# The script automatically allows Docker bridge networks (172.16-31.0.0/12)
# in addition to localhost.

set -euo pipefail

ZABBIX_SERVER="${1:?Usage: $0 ZABBIX_SERVER_IP [HOSTNAME] [ALLOW_NETWORKS]}"
HOSTNAME="${2:-$(hostname -f)}"
EXTRA_ALLOW="${3:-}"
ZABBIX_VERSION="7.0"

echo "=== Installing Zabbix Agent2 ==="
echo "Server: ${ZABBIX_SERVER}"
echo "Hostname: ${HOSTNAME}"

# Add Zabbix repository
wget -q "https://repo.zabbix.com/zabbix/${ZABBIX_VERSION}/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu$(lsb_release -rs)_all.deb" -O /tmp/zabbix-release.deb 2>/dev/null || {
    echo "Ubuntu repo not found, trying Debian..."
    wget -q "https://repo.zabbix.com/zabbix/${ZABBIX_VERSION}/debian/pool/main/z/zabbix-release/zabbix-release_latest+debian12_all.deb" -O /tmp/zabbix-release.deb
}
sudo dpkg -i /tmp/zabbix-release.deb
sudo apt-get update -qq

# Install agent2 (stop service before config to avoid dpkg restart failure)
sudo apt-get install -y --no-starts zabbix-agent2 zabbix-agent2-plugin-postgresql 2>/dev/null || {
    # If install fails due to missing config, write minimal config first
    sudo mkdir -p /etc/zabbix
    sudo tee /etc/zabbix/zabbix_agent2.conf > /dev/null <<EOFMIN
# Minimal placeholder - will be replaced below
Server=127.0.0.1
ServerActive=127.0.0.1:10051
Hostname=$(hostname -f)
EOFMIN
    sudo dpkg --configure -a
}

# Build Server allow list: localhost + Docker networks + any extra
ALLOW_LIST="127.0.0.1"
# Add the zabbix server IP itself
ALLOW_LIST="${ALLOW_LIST},${ZABBIX_SERVER}"
# Docker bridge networks (172.16.0.0/12 covers 172.16-31.x.x)
ALLOW_LIST="${ALLOW_LIST},172.16.0.0/12"
# Common private ranges
ALLOW_LIST="${ALLOW_LIST},192.168.0.0/16,10.0.0.0/8"
# Extra networks from argument
if [ -n "${EXTRA_ALLOW}" ]; then
    ALLOW_LIST="${ALLOW_LIST},${EXTRA_ALLOW}"
fi

# Host metadata for autoregistration
HOST_META="Linux"
command -v docker >/dev/null 2>&1 && HOST_META="Linux Docker"

# Configure agent
sudo tee /etc/zabbix/zabbix_agent2.conf > /dev/null <<EOF
# Zabbix Agent2 Configuration
# Auto-generated by HomePilot monitoring setup

# Server connections — allow localhost, Docker networks, and private ranges
Server=${ALLOW_LIST}
ServerActive=${ZABBIX_SERVER}:10051

# Host metadata for autoregistration
HostMetadata=${HOST_META}

# Hostname
Hostname=${HOSTNAME}

# Logging
LogFile=/var/log/zabbix/zabbix_agent2.log
LogFileSize=10
DebugLevel=3

# Active checks
RefreshActiveChecks=120
BufferSend=5
BufferSize=1000

# Timeout
Timeout=10
EOF

# Enable Docker monitoring if Docker is present
if command -v docker >/dev/null 2>&1; then
    echo "Docker detected — enabling Docker plugin"
    sudo usermod -aG docker zabbix 2>/dev/null || true
    sudo mkdir -p /etc/zabbix/zabbix_agent2.d
    sudo tee /etc/zabbix/zabbix_agent2.d/docker.conf > /dev/null <<EOF
# Docker monitoring via agent2 plugin
EOF
fi

# Enable PostgreSQL plugin
sudo mkdir -p /etc/zabbix/zabbix_agent2.d
sudo tee /etc/zabbix/zabbix_agent2.d/postgresql.conf > /dev/null <<EOF
# PostgreSQL monitoring via agent2 plugin
EOF

# Start and enable
sudo systemctl restart zabbix-agent2
sudo systemctl enable zabbix-agent2

echo ""
echo "=== Zabbix Agent2 Installed ==="
echo "Server: ${ZABBIX_SERVER}:10051"
echo "Hostname: ${HOSTNAME}"
echo "Auto-registration metadata: ${HOST_META}"
echo "Allowed servers: ${ALLOW_LIST}"
echo "Docker plugin: $(command -v docker >/dev/null 2>&1 && echo "enabled" || echo "not available")"
echo ""
echo "Check status: sudo systemctl status zabbix-agent2"
echo "Check logs: sudo tail -f /var/log/zabbix/zabbix_agent2.log"